#!/bin/bash
#
# Notify of Homebrew updates via Notification Center on Mac OS X
#
# Author: Chris Streeter http://www.chrisstreeter.com
# Requires: terminal-notifier. Install with:
#   gem install terminal-notifier

# Locate brew (not on PATH under launchd), then derive everything from its prefix
BREW_EXEC="$(command -v brew || echo /opt/homebrew/bin/brew)"
[ -x "$BREW_EXEC" ] || exit 0
TERMINAL_NOTIFIER="$("$BREW_EXEC" --prefix)/bin/terminal-notifier"
[ -x "$TERMINAL_NOTIFIER" ] || exit 0
NOTIF_ARGS="-activate com.apple.Terminal -contentImage https://brew.sh/img/homebrew-256x256.png"

$BREW_EXEC update 2>&1 > /dev/null
outdated=`$BREW_EXEC outdated | tr ' ' '\n'`

if [ -z "$outdated" ] ; then
	# No updates available
	$TERMINAL_NOTIFIER $NOTIF_ARGS \
		-title "No Homebrew Updates Available" \
		-message "No updates available yet for any homebrew packages."
else
	# We've got an outdated formula or two
	lc=$((`echo "$outdated" | wc -l`))
	outdated=`echo "$outdated" | tail -$lc`
	message=`echo "$outdated" | head -5`
	if [ "$outdated" != "$message" ]; then
		message="Some of the outdated formulae are:
$message"
	else
		message="The following formulae are outdated:
$message"
	fi
	# Send to the Notification Center
	$TERMINAL_NOTIFIER $NOTIF_ARGS \
		-title "Homebrew Update(s) Available" \
		-message "$message"
fi
